In [2]:
import torch


1. Illustrate the functions for Reshaping, viewing, stacking, squeezing and unsqueezing of tensors
2. Illustrate the use of torch.permute().
3. Illustrate indexing in tensors
4. Show how numpy arrays are converted to tensors and back again to numpy arrays
5. Create a random tensor with shape (7, 7).
6. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
7. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
8. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
9. Find the maximum and minimum values of the output of 7.
10. Find the maximum and minimum index values of the output of 7.
11. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [6]:
# 1. Illustrate the functions for Reshaping, viewing, stacking, squeezing and unsqueezing of tensors

x = torch.tensor([1,2,3,4,5,6,7,8])
print(x)

a = torch.reshape(x, (2,4))
print(a)

b = x.view(4,2)
print(b)

y = torch.tensor([8,7,6,5,4,3,2,1])
c = torch.stack((x, y))
print(c)

d = x.unsqueeze(0)
print(d)

e = x.squeeze(0)
print(e)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 3, 4, 5, 6, 7, 8],
        [8, 7, 6, 5, 4, 3, 2, 1]])
tensor([[1, 2, 3, 4, 5, 6, 7, 8]])
tensor([1, 2, 3, 4, 5, 6, 7, 8])


In [20]:
# 2. Illustrate the use of torch.permute().

f = torch.permute(torch.rand(1,15), (1,0))
print(f)

tensor([[0.8235],
        [0.8607],
        [0.7482],
        [0.4869],
        [0.3844],
        [0.1196],
        [0.6136],
        [0.5091],
        [0.9383],
        [0.6511],
        [0.0441],
        [0.8830],
        [0.9470],
        [0.1353],
        [0.8026]])


In [13]:
# 3. Illustrate indexing in tensors
print(x[1])

tensor(2)


In [17]:
# 4. Show how numpy arrays are converted to tensors and back again to numpy arrays
x_numpy = x.numpy()
print(x_numpy)

print(torch.tensor(x_numpy))

[1 2 3 4 5 6 7 8]
tensor([1, 2, 3, 4, 5, 6, 7, 8])


In [18]:
# 5. Create a random tensor with shape (7, 7).
print(torch.rand(7,7))

tensor([[0.7150, 0.4120, 0.1911, 0.6737, 0.2564, 0.0941, 0.1654],
        [0.8229, 0.1028, 0.1287, 0.3222, 0.3788, 0.7435, 0.4632],
        [0.7434, 0.1306, 0.9717, 0.8176, 0.2788, 0.2249, 0.9141],
        [0.8360, 0.7689, 0.7021, 0.6955, 0.4066, 0.3882, 0.3857],
        [0.2220, 0.2081, 0.3339, 0.7012, 0.2692, 0.3479, 0.0757],
        [0.1755, 0.1983, 0.7038, 0.9828, 0.5562, 0.6484, 0.6930],
        [0.5129, 0.7152, 0.1192, 0.7621, 0.4944, 0.4545, 0.2721]])


In [23]:
# 6. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
g = torch.matmul(f, torch.rand(1, 7))
g

tensor([[0.4927, 0.3538, 0.1018, 0.1310, 0.5733, 0.8031, 0.1505],
        [0.5150, 0.3698, 0.1064, 0.1369, 0.5992, 0.8395, 0.1573],
        [0.4477, 0.3215, 0.0925, 0.1190, 0.5209, 0.7298, 0.1367],
        [0.2913, 0.2092, 0.0602, 0.0775, 0.3389, 0.4748, 0.0890],
        [0.2300, 0.1652, 0.0475, 0.0612, 0.2676, 0.3749, 0.0702],
        [0.0716, 0.0514, 0.0148, 0.0190, 0.0833, 0.1167, 0.0219],
        [0.3671, 0.2636, 0.0758, 0.0976, 0.4271, 0.5984, 0.1121],
        [0.3046, 0.2187, 0.0629, 0.0810, 0.3544, 0.4965, 0.0930],
        [0.5614, 0.4032, 0.1159, 0.1493, 0.6532, 0.9151, 0.1714],
        [0.3896, 0.2798, 0.0805, 0.1036, 0.4533, 0.6350, 0.1190],
        [0.0264, 0.0190, 0.0054, 0.0070, 0.0307, 0.0430, 0.0081],
        [0.5283, 0.3794, 0.1091, 0.1405, 0.6147, 0.8612, 0.1613],
        [0.5667, 0.4069, 0.1170, 0.1507, 0.6593, 0.9237, 0.1730],
        [0.0810, 0.0581, 0.0167, 0.0215, 0.0942, 0.1320, 0.0247],
        [0.4802, 0.3448, 0.0992, 0.1277, 0.5587, 0.7828, 0.1466]])

In [24]:
# 7. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).

h = torch.rand(2,3).to("cuda")
i = torch.rand(2,3).to("cuda")

print(h)
print(i)

tensor([[0.7162, 0.4483, 0.1015],
        [0.4621, 0.7848, 0.7272]], device='cuda:0')
tensor([[0.4813, 0.8178, 0.5496],
        [0.3843, 0.8252, 0.3097]], device='cuda:0')


In [26]:
# 8. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
j = torch.matmul(g, g.T)
j

tensor([[1.3918, 1.4547, 1.2646, 0.8229, 0.6497, 0.2022, 1.0370, 0.8605, 1.5859,
         1.1005, 0.0745, 1.4923, 1.6006, 0.2287, 1.3565],
        [1.4547, 1.5205, 1.3218, 0.8601, 0.6791, 0.2114, 1.0839, 0.8994, 1.6576,
         1.1503, 0.0779, 1.5598, 1.6730, 0.2390, 1.4179],
        [1.2646, 1.3218, 1.1491, 0.7477, 0.5903, 0.1837, 0.9422, 0.7818, 1.4410,
         0.9999, 0.0677, 1.3560, 1.4544, 0.2078, 1.2326],
        [0.8229, 0.8601, 0.7477, 0.4865, 0.3841, 0.1196, 0.6131, 0.5087, 0.9376,
         0.6506, 0.0441, 0.8823, 0.9463, 0.1352, 0.8020],
        [0.6497, 0.6791, 0.5903, 0.3841, 0.3033, 0.0944, 0.4841, 0.4016, 0.7403,
         0.5137, 0.0348, 0.6966, 0.7472, 0.1068, 0.6332],
        [0.2022, 0.2114, 0.1837, 0.1196, 0.0944, 0.0294, 0.1507, 0.1250, 0.2304,
         0.1599, 0.0108, 0.2168, 0.2326, 0.0332, 0.1971],
        [1.0370, 1.0839, 0.9422, 0.6131, 0.4841, 0.1507, 0.7726, 0.6411, 1.1816,
         0.8199, 0.0555, 1.1119, 1.1926, 0.1704, 1.0107],
        [0.8605, 0.8994, 0.

In [28]:
# 9. Find the maximum and minimum values of the output of 7.

print(torch.max(h))
print(torch.min(h))

tensor(0.7848, device='cuda:0')
tensor(0.1015, device='cuda:0')


In [31]:
# 10. Find the maximum and minimum index values of the output of 7.
print(torch.argmax(h))
print(torch.argmin(h))

tensor(4, device='cuda:0')
tensor(2, device='cuda:0')


In [34]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
torch.manual_seed(7)
k = torch.rand((1,1,1,10))
l = k[0,0,0,:]

print(k)
print(k.shape)

print('----')

print(l)
print(l.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
----
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
